# Generated by Django 4.2.5 on 2023-09-15 08:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
