# Generated by Django 4.2.5 on 2023-09-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_platform_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(to='store.developer'),
        ),
    ]
